### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by cmt227** [OpenMusicKontrollers/sherlock.lv2#1]
Hi,

Thanks for your work on open source music software.
I'm running up-to-date Arch Linux, and I think I have all dependencies installed for Sherlock.
I get build errors that the attached file points out. Thanks for any help.

-Carsten
[build.txt](https://github.com/OpenMusicKontrollers/sherlock.lv2/files/196159/build.txt)

**Comment by cmt227** [comment]
I also get the same error when building the package from the Arch User Repositories

**Comment by ventosus** [comment]
I cannot reproduce this here.

It seems that LV2 headers are not correclty resolved on your system.

Do you have an up-to-date LV2 installation? e.g. 'pkg-config --modversion lv2' -> 0.12.0
https://www.archlinux.org/packages/extra/x86_64/lv2/

P.s. I've fixed the cmake configure script to give less verbose warnings when compiling with GCC, you may want to pull from HEAD.

**Comment by cmt227** [comment]
Awesome, I got it to work. There were lv2 directories in both /usr/include; /usr/bin; /usr/lib; as well as in /usr/local/... etc. I removed the ones in /usr/local and everything works now. Thanks!!

I'll mark this as resolved, and do some more research about the proper lv2 configuration.
