### ISSUE TITLE
Compilation problems under fedora 24

### ISSUE THREAD

**Issue by ycollet** [OpenMusicKontrollers/sherlock.lv2#2]
Hello

I am trying to compile sherlock on Fedora 24.

**Comment by ycollet** [comment]
Oups ...
Under fedora, the version of LV2 is 1.10.0.
Here is the here message I've got:
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc_inspector.c:23:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/util.h: Dans la fonction ‘lv2_osc_body_unroll’:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/util.h:437:3: erreur : ‘LV2_Atom_Tuple {alias const struct <anonymous>}’ has no member named ‘size’
   LV2_ATOM_TUPLE_FOREACH(items, atom)
   ^~
CMakeFiles/sherlock.dir/build.make:134 : la recette pour la cible « CMakeFiles/sherlock.dir/osc_inspector.c.o » a échouée

Best regards,

YC

**Comment by ycollet** [comment]
Here are some more error messages when I try to compile the osc.lv2 part:

In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h: Dans la fonction ‘lv2_osc_reader_arg_varlist’:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:483:42: attention : implicit declaration of function ‘va_arg’ [-Wimplicit-function-declaration]
     if(!lv2_osc_reader_get_int32(reader, va_arg(args, int32_t *)))
                                          ^~~~~~
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:483:55: erreur : expected expression before ‘int32_t’
     if(!lv2_osc_reader_get_int32(reader, va_arg(args, int32_t *)))
                                                       ^~~~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:487:55: erreur : expected expression before ‘float’
     if(!lv2_osc_reader_get_float(reader, va_arg(args, float *)))
                                                       ^~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:491:56: erreur : expected expression before ‘const’
     if(!lv2_osc_reader_get_string(reader, va_arg(args, const char **)))
                                                        ^~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:495:54: erreur : expected expression before ‘int32_t’
     if(!lv2_osc_reader_get_blob(reader, va_arg(args, int32_t *), va_arg(args, const uint8_t **)))
                                                      ^~~~~~~
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:495:79: erreur : expected expression before ‘const’
     if(!lv2_osc_reader_get_blob(reader, va_arg(args, int32_t *), va_arg(args, const uint8_t **)))
                                                                               ^~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:506:55: erreur : expected expression before ‘int64_t’
     if(!lv2_osc_reader_get_int64(reader, va_arg(args, int64_t *)))
                                                       ^~~~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:510:56: erreur : expected expression before ‘double’
     if(!lv2_osc_reader_get_double(reader, va_arg(args, double *)))
                                                        ^~~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:514:57: erreur : expected expression before ‘uint64_t’
     if(!lv2_osc_reader_get_timetag(reader, va_arg(args, uint64_t *)))
                                                         ^~~~~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:519:54: erreur : expected expression before ‘const’
     if(!lv2_osc_reader_get_midi(reader, va_arg(args, const uint8_t **)))
                                                      ^~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:523:56: erreur : expected expression before ‘const’
     if(!lv2_osc_reader_get_symbol(reader, va_arg(args, const char **)))
                                                        ^~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:527:54: erreur : expected expression before ‘char’
     if(!lv2_osc_reader_get_char(reader, va_arg(args, char *)))
                                                      ^~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:531:54: erreur : expected expression before ‘uint8_t’
     if(!lv2_osc_reader_get_rgba(reader, va_arg(args, uint8_t *), va_arg(args, uint8_t *),
                                                      ^~~~~~~
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:531:79: erreur : expected expression before ‘uint8_t’
     if(!lv2_osc_reader_get_rgba(reader, va_arg(args, uint8_t *), va_arg(args, uint8_t *),
                                                                               ^~~~~~~
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:532:20: erreur : expected expression before ‘uint8_t’
       va_arg(args, uint8_t *), va_arg(args, uint8_t *)))
                    ^~~~~~~
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:532:45: erreur : expected expression before ‘uint8_t’
       va_arg(args, uint8_t *), va_arg(args, uint8_t *)))
                                             ^~~~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h: Dans la fonction ‘lv2_osc_reader_arg_vararg’:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:545:3: attention : implicit declaration of function ‘va_start’ [-Wimplicit-function-declaration]
   va_start(args, fmt);
   ^~~~~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:6:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/reader.h:549:2: attention : implicit declaration of function ‘va_end’ [-Wimplicit-function-declaration]
  va_end(args);
  ^~~~~~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/writer.h:25:0,
                 from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:7:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/util.h: Dans la fonction ‘lv2_osc_body_unroll’:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/util.h:437:3: erreur : ‘LV2_Atom_Tuple {alias const struct <anonymous>}’ has no member named ‘size’
   LV2_ATOM_TUPLE_FOREACH(items, atom)
   ^~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:7:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/writer.h: Dans la fonction ‘lv2_osc_writer_packet’:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/writer.h:432:3: erreur : ‘LV2_Atom_Tuple {alias const struct <anonymous>}’ has no member named ‘size’
   LV2_ATOM_TUPLE_FOREACH(items, atom)
   ^~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:7:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/writer.h:459:4: erreur : ‘LV2_Atom_Tuple {alias const struct <anonymous>}’ has no member named ‘size’
    LV2_ATOM_TUPLE_FOREACH(arguments, atom)
    ^~
In file included from /home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc_test.c:7:0:
/home/collette/repositories/LV2/OpenKontroller/sherlock.lv2/osc.lv2/osc.lv2/writer.h:467:4: erreur : ‘LV2_Atom_Tuple {alias const struct <anonymous>}’ has no member named ‘size’
    LV2_ATOM_TUPLE_FOREACH(arguments, atom)
    ^~
CMakeFiles/osc_test.dir/build.make:62 : la recette pour la cible « CMakeFiles/osc_test.dir/osc_test.c.o » a échouée
make[2]: *** [CMakeFiles/osc_test.dir/osc_test.c.o] Erreur 1

**Comment by ventosus** [comment]
There is a bug for LV2_ATOM_TUPLE_FOREACH in LV2 < 1.12.0
http://lv2plug.in/git/cgit.cgi/lv2.git/commit/?id=479843fc4dfaafdba49cf024115261c20abeb89d

the macro was not properly overwritten, it seems

fixed in e88b4e

**Comment by ycollet** [comment]
Thanks a lot, it compiles fine now.

**Comment by ycollet** [comment]
eteroj.lv2 has the same problem

**Comment by ycollet** [comment]
synthpod has the same problem too.

**Comment by ventosus** [comment]
eteroj.lv2 has been fixed in
https://github.com/OpenMusicKontrollers/eteroj.lv2/commit/96000407287612a50108386bf1770e55da71a8ba

synthpod has been fixed in
https://github.com/OpenMusicKontrollers/synthpod/commit/f231c9184ab45740e2de1be9d8b3627841249d5f
