### ISSUE TITLE
Please add the README section how to use sherlock.lv2

### ISSUE THREAD

**Issue by yurivict** [OpenMusicKontrollers/sherlock.lv2#3]
Please provide sample commands how to use it, and how to get to screens like these: https://open-music-kontrollers.ch/lv2/sherlock/

**Comment by ventosus** [comment]
well, it's an LV2 plugin, just install it and load it in your favorite LV2 host, there's no magic involved

**Comment by yurivict** [comment]
Now I see that windows appear when I load it.

Thanks!
