### ISSUE TITLE
Default window size cuts off text

### ISSUE THREAD

**Issue by mxmilkiib** [OpenMusicKontrollers/sherlock.lv2#4]
![image](https://user-images.githubusercontent.com/108225/93622303-cdd6a280-f9d4-11ea-97ae-1f71b29170c2.png)

If I turn off follow, I get;
![image](https://user-images.githubusercontent.com/108225/93622338-dcbd5500-f9d4-11ea-8805-837209084aa2.png)

**Comment by ventosus** [comment]
thanks for reporting, can reproduce

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/15>
