### ISSUE TITLE
Unable to use on Ubuntu 20.04

### ISSUE THREAD

**Issue by windowsrefund** [OpenMusicKontrollers/sherlock.lv2#6]
Steps to reproduce with Carla 2.3.0

1. Unzip and copy sherlock.lv2-0.28.0/x86_64-linux-gnu-bullseye/sherlock.lv2 directory to ~/.lv2
2. Start Carla
3. Load plugin

Result: Plugin appears to load but no GUI cog is made available.

The plugin also segfaults qtractor 0.9.22 when loaded.

**Comment by windowsrefund** [comment]
Some progress has been made by installing a package called libglew-dev. After loading in Carla 2.3.0, the cog wheel used to display the plugin's GUI is now available. Clicking on it however, does crash the plugin

```
Will use LV2 X11 UI for 'Sherlock MIDI Inspector'
Carla Bridge Ready!
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  35
  Current serial number in output stream:  35
Carla assertion failure: "engine == nullptr" in file ../backend/CarlaHostImpl.hpp, line 86
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
```

**Comment by ventosus** [comment]
1. As the name implies,  that binary is for Debian Bullseye, not for Ubuntu - it may work - or it may not work
2. Do you habe all dependencies installed? What is the output of the following command?

    ldd ~/.lv2/sherlock.lv2/*.so

**Comment by ventosus** [comment]
Easiest way to install on Ubuntu mot probably is by activating the KX repos [1].

[1] https://kx.studio/Repositories

**Comment by windowsrefund** [comment]
I mean, Ubuntu is just debian with a bunch of other crap so I figured I'd raise the issue. I didn't know this was hosted in kxstudio so I'll see what installing that older version does. Thank you.

**Comment by windowsrefund** [comment]
Resolved :)
`mv ~/.config/falkTX{,.bak}`
